### ISSUE TITLE
Long abstract results in header at bottom of page

### ISSUE THREAD

**Issue by amcpherson** [rchurchley/thesis-template#15]
If the abstract is longer than half a page, the ABSTRACT header appears at the bottom of the page.

**Comment by rchurchley** [comment]
I have been able to reproduce this, but only by making the Abstract exceed roughly 30 lines --- the point at which the header, abstract, and keywords would no longer fit on a single page. This behaviour is caused by the code which normally centers the abstract on its page.

The usual layout is

```
\vfill
ABSTRACT
Text of the abstract
Keywords
\vfill
```

but if LaTeX needs to insert a page break in the abstract environment, it chooses:

```
\vfill
ABSTRACT
---page break---
Text of the abstract
Keywords
\vfill
```

This has the effect of putting the abstract header on the bottom of its own page, with the abstract text and keywords on subsequent pages.

In a sense this is not a bug, since it only occurs when the abstract is [too long according to the library's requirements](http://www.lib.sfu.ca/help/writing/thesis/format/abstract). But it's probably still undesirable, as users won't realize they need to shorten their abstract to fix it.

I think the safest solution is to abandon the vertically centered abstract and to format it (and the other frontmatter sections) normally. By setting the headers with `\chapter*{...}` instead of manually, we put the frontmatter formatting more in line with the Word template and avoid unexpected behaviour like this. I have implemented this change in 4388da7.
